# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-16 03:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('medicalcontrol', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalcontrol',
            name='photo_first',
            field=models.ImageField(default=1, upload_to='medicalcontrol/%Y/%m/%d/', verbose_name='foto 1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicalcontrol',
            name='photo_second',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='medicalcontrol/%Y/%m/%d/', verbose_name='foto 2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicalcontrol',
            name='photo_third',
            field=models.ImageField(default=1, upload_to='medicalcontrol/%Y/%m/%d/', verbose_name='foto 3'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medicalcontrol',
            name='medic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Person', verbose_name='medic'),
        ),
        migrations.AlterField(
            model_name='medicalcontrol',
            name='natural_key',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name', verbose_name='nemotécnico'),
        ),
    ]
