# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-16 03:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
        ('medicalcontrol', '0002_auto_20170816_0306'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalcontrol',
            name='supplies',
            field=models.ManyToManyField(to='pharmacy.SupplyAssignControl'),
        ),
    ]
