# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-16 03:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalcontrol', '0003_medicalcontrol_supplies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalcontrol',
            name='supplies',
            field=models.ManyToManyField(blank=True, to='pharmacy.SupplyAssignControl'),
        ),
    ]
