# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-16 03:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalcontrol', '0004_auto_20170816_0346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalcontrol',
            name='photo_first',
            field=models.ImageField(blank=True, null=True, upload_to='medicalcontrol/%Y/%m/%d/', verbose_name='foto 1'),
        ),
        migrations.AlterField(
            model_name='medicalcontrol',
            name='photo_second',
            field=models.ImageField(blank=True, null=True, upload_to='medicalcontrol/%Y/%m/%d/', verbose_name='foto 2'),
        ),
        migrations.AlterField(
            model_name='medicalcontrol',
            name='photo_third',
            field=models.ImageField(blank=True, null=True, upload_to='medicalcontrol/%Y/%m/%d/', verbose_name='foto 3'),
        ),
    ]
