# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 06:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animalbreed',
            options={'verbose_name': 'raza', 'verbose_name_plural': 'razas'},
        ),
        migrations.AlterModelOptions(
            name='animaltype',
            options={'verbose_name': 'tipo de animal', 'verbose_name_plural': 'tipo de animales'},
        ),
        migrations.AlterModelOptions(
            name='color',
            options={'verbose_name_plural': 'colores'},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'verbose_name': 'paciente', 'verbose_name_plural': 'pacientes'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'persona'},
        ),
        migrations.AddField(
            model_name='patient',
            name='color_first',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='color_first', to='core.Color', verbose_name='color primario'),
        ),
        migrations.AddField(
            model_name='patient',
            name='color_second',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='color_second', to='core.Color', verbose_name='color secundario'),
        ),
        migrations.AddField(
            model_name='patient',
            name='photo_first',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='patient/%Y/%m/%d/', verbose_name='foto 1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='photo_second',
            field=models.ImageField(default=1, upload_to='patient/%Y/%m/%d/', verbose_name='foto 2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='photo_third',
            field=models.ImageField(default='', upload_to='patient/%Y/%m/%d/', verbose_name='foto 3'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='animalbreed',
            name='animal_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.AnimalType'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='animal_breed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.AnimalBreed', verbose_name='raza / tipo de animal'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Person', verbose_name='autor'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='name',
            field=models.CharField(max_length=10, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='natural_key',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name', verbose_name='nemotécnico'),
        ),
    ]
