# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 20:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='photo_first',
            field=models.ImageField(default=1, upload_to='patient'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='photo_second',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='patient'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='photo_third',
            field=models.ImageField(default=-2017, upload_to='patient'),
            preserve_default=False,
        ),
    ]
