# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-16 04:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_patient_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='photo_first',
            field=models.ImageField(blank=True, null=True, upload_to='patient/%Y/%m/%d/', verbose_name='foto 1'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='photo_second',
            field=models.ImageField(blank=True, null=True, upload_to='patient/%Y/%m/%d/', verbose_name='foto 2'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='photo_third',
            field=models.ImageField(blank=True, null=True, upload_to='patient/%Y/%m/%d/', verbose_name='foto 3'),
        ),
    ]
