# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-15 20:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('natural_key', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name')),
                ('description', models.TextField()),
                ('stocks', models.DecimalField(blank=True, decimal_places=1, max_digits=15, null=True)),
            ],
            options={
                'verbose_name': 'suministro',
            },
        ),
        migrations.CreateModel(
            name='SupplyAssignControl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('code_supply', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('supply', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pharmacy.Supply')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Person')),
            ],
            options={
                'verbose_name': 'asignación de suministro a control',
            },
        ),
        migrations.CreateModel(
            name='SupplyMovement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('code_supply', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('expire_date', models.DateField()),
                ('supply', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pharmacy.Supply')),
            ],
            options={
                'verbose_name': 'movimiento',
            },
        ),
        migrations.CreateModel(
            name='TypeSupplyMovement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('natural_key', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name')),
            ],
            options={
                'verbose_name': 'tipo de movimiento',
                'verbose_name_plural': 'tipo de movimientos',
            },
        ),
        migrations.CreateModel(
            name='UnitOfMeasurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('natural_key', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name')),
            ],
            options={
                'verbose_name': 'unidad de medida',
                'verbose_name_plural': 'unidades de medida',
            },
        ),
        migrations.AddField(
            model_name='supplymovement',
            name='type_supply_movement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pharmacy.TypeSupplyMovement'),
        ),
        migrations.AddField(
            model_name='supplymovement',
            name='user_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_from', to='core.Participant'),
        ),
        migrations.AddField(
            model_name='supplymovement',
            name='user_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_to', to='core.Participant'),
        ),
        migrations.AddField(
            model_name='supply',
            name='unit_of_measurement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pharmacy.UnitOfMeasurement'),
        ),
    ]
